/*
 * Copyright (c) 2013-2014 Conformal Systems <info@conformal.com>
 *
 * This file originated from: http://opensource.conformal.com/
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef __GDK_ATOM_GO_H__
#define __GDK_ATOM_GO_H__

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <gdk/gdk.h>

const GdkAtom _GDK_SELECTION_PRIMARY = GDK_SELECTION_PRIMARY;
const GdkAtom _GDK_SELECTION_SECONDARY = GDK_SELECTION_SECONDARY;
const GdkAtom _GDK_SELECTION_CLIPBOARD = GDK_SELECTION_CLIPBOARD;
const GdkAtom _GDK_TARGET_BITMAP = GDK_TARGET_BITMAP;
const GdkAtom _GDK_TARGET_COLORMAP = GDK_TARGET_COLORMAP;
const GdkAtom _GDK_TARGET_DRAWABLE = GDK_TARGET_DRAWABLE;
const GdkAtom _GDK_TARGET_PIXMAP = GDK_TARGET_PIXMAP;
const GdkAtom _GDK_TARGET_STRING = GDK_TARGET_STRING;
const GdkAtom _GDK_SELECTION_TYPE_ATOM = GDK_SELECTION_TYPE_ATOM;
const GdkAtom _GDK_SELECTION_TYPE_BITMAP = GDK_SELECTION_TYPE_BITMAP;
const GdkAtom _GDK_SELECTION_TYPE_COLORMAP = GDK_SELECTION_TYPE_COLORMAP;
const GdkAtom _GDK_SELECTION_TYPE_DRAWABLE = GDK_SELECTION_TYPE_DRAWABLE;
const GdkAtom _GDK_SELECTION_TYPE_INTEGER = GDK_SELECTION_TYPE_INTEGER;
const GdkAtom _GDK_SELECTION_TYPE_PIXMAP = GDK_SELECTION_TYPE_PIXMAP;
const GdkAtom _GDK_SELECTION_TYPE_WINDOW = GDK_SELECTION_TYPE_WINDOW;
const GdkAtom _GDK_SELECTION_TYPE_STRING = GDK_SELECTION_TYPE_STRING;

#endif
